### ISSUE TITLE
Solution: auto-delete.trigger queue is down or inaccessible

### ISSUE THREAD

**Issue by wokim** [spearhead-ea/island#148]
There is a problem that island cannot restart when one of the nodes in the PushMQ cluster is unexpectedly shutdown.

**Steps**
1. Run PushMQ and island.
2. Identify the master node of the auto-delete.trigger queue.
3. Shut down the node and check the island state.
4. You can see the following error through the console log

> [--------] 2017-09-26T07:28:43.795Z info Service [[ asset-island ]] Starting! Version is [[ 162696-rl.m.cn.cbt ]]
[--------] 2017-09-26T07:28:43.818Z info connecting to broker { url: 'amqp://island:devenv@rmqrpc.set7006.svr.nfsol.db:5671', poolSize: '100' }
[--------] 2017-09-26T07:28:43.822Z info connecting to broker { url: 'amqp://island:devenv@rmqevent.set7006.svr.nfsol.db:5672', poolSize: '100' }
[--------] 2017-09-26T07:28:43.823Z info connecting to broker { url: 'amqp://island:devenv@rmqpush.set7006.svr.nfsol.db:5673', poolSize: '100' }
[--------] 2017-09-26T07:28:43.905Z info connected to amqp://island:devenv@rmqrpc.set7006.svr.nfsol.db:5671
[--------] 2017-09-26T07:28:43.976Z info connected to amqp://island:devenv@rmqpush.set7006.svr.nfsol.db:5673
[--------] 2017-09-26T07:28:43.986Z info consuming rpc.res.asset-island.set7006-asset-1-2c8ck.6406870c-bfe5-49ab-b220-83a86e46a409
[--------] 2017-09-26T07:28:43.994Z info connected to amqp://island:devenv@rmqevent.set7006.svr.nfsol.db:5672
[--------] 2017-09-26T07:28:44.014Z notice amqp channel error: {"message":"Channel closed by server: 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rmq-push@NFS-7006-RMQ-MIXED-4' of durable queue 'auto-delete.trigger' in vhost '/' is down or inaccessible\"","stack":"Error: Channel closed by server: 404 (NOT-FOUND) with message \"NOT_FOUND - home node 'rmq-push@NFS-7006-RMQ-MIXED-4' of durable queue 'auto-delete.trigger' in vhost '/' is down or inaccessible\"\n    at Channel.C.accept (/app/be/node_modules/amqplib/lib/channel.js:406:17)\n    at Connection.mainAccept [as accept] (/app/be/node_modules/amqplib/lib/connection.js:63:33)\n    at Socket.go (/app/be/node_modules/amqplib/lib/connection.js:476:48)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at emitReadable_ (_stream_readable.js:432:10)\n    at emitReadable (_stream_readable.js:426:7)\n    at readableAddChunk (_stream_readable.js:187:13)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread [as _originalOnread] (net.js:551:20)\n    at TCP.onread (/app/be/node_modules/async-listener/glue.js:188:31)","code":404}
[--------] 2017-09-26T07:28:44.014Z debug Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - home node 'rmq-push@NFS-7006-RMQ-MIXED-4' of durable queue 'auto-delete.trigger' in vhost '/' is down or inaccessible"
          at Channel.C.accept (/app/be/node_modules/amqplib/lib/channel.js:406:17)
          at Connection.mainAccept [as accept] (/app/be/node_modules/amqplib/lib/connection.js:63:33)
          at Socket.go (/app/be/node_modules/amqplib/lib/connection.js:476:48)
          at emitNone (events.js:86:13)
          at Socket.emit (events.js:185:7)
          at emitReadable_ (_stream_readable.js:432:10)
          at emitReadable (_stream_readable.js:426:7)
          at readableAddChunk (_stream_readable.js:187:13)
          at Socket.Readable.push (_stream_readable.js:134:10)
          at TCP.onread [as _originalOnread] (net.js:551:20)
          at TCP.onread (/app/be/node_modules/async-listener/glue.js:188:31)
     failed to initialize Error: Operation failed: QueueDeclare; 404 (NOT-FOUND) with message "NOT_FOUND - home node 'rmq-push@NFS-7006-RMQ-MIXED-4' of durable queue 'auto-delete.trigger' in vhost '/' is down or inaccessible"
         at reply (/app/be/node_modules/amqplib/lib/channel.js:127:17)
         at Channel.C.accept (/app/be/node_modules/amqplib/lib/channel.js:401:7)
         at Connection.mainAccept [as accept] (/app/be/node_modules/amqplib/lib/connection.js:63:33)
         at Socket.go (/app/be/node_modules/amqplib/lib/connection.js:476:48)
         at emitNone (events.js:86:13)
         at Socket.emit (events.js:185:7)
         at emitReadable_ (_stream_readable.js:432:10)
         at emitReadable (_stream_readable.js:426:7)
         at readableAddChunk (_stream_readable.js:187:13)
         at Socket.Readable.push (_stream_readable.js:134:10)
         at TCP.onread [as _originalOnread] (net.js:551:20)
         at TCP.onread (/app/be/node_modules/async-listener/glue.js:188:31)

**Solution**
`$ rabbitmqctl set_policy mirror "auto-delete.trigger '{"queue-master-locator":"random","ha-mode":"all"}' --priority 2 --apply-to queues`

**Comment by heycalmdown** [comment]
Can #142 fix this?
